### ISSUE TITLE
Feature Request : Docker

### ISSUE THREAD

**Issue by clawfire** [puphpet/puphpet#1231]
Hi ;)

I would like to see a docker support, would be great as vagrant is now supporting docker as a provider.

**Comment by jjelev** [comment]
Actually containers are better. But yes there is no purpose to include a Docker (Docker Compose) management in this project. Docker orchestration is not so advanced yet but microservices are making their way very fast. From a dev perspective - running containers on my machine is a lot faster, lighter and more flexible to provision than vagrant solution. But at the end of the day we all want to push our code to production. Orchestrating production environment with vagrant plugin? No way, simply I don't trust Vagrant. The main reason of not using LAMP stack is to be as close as possible to actual environment. When you have an orchestration solution and using it only on dev, you miss the whole idea.

**Comment by MichaelMackus** [comment]
@clawfire and @jjelev I've been using docker exclusively for my dev setup lately. Puphpet is great for out of the box (with GUI config), but I prefer the lightweight & performance of docker (esp. on linux hosts). Check out [this repo](https://github.com/teneleven/teneleven-puppet) for a little insight.

For instance, with this you can do 

```puppet
teneleven::container::provision { 'mysite':
  volumes => ["${::volume_dir}/www/mysite:/var/www"]
}
```

Then in hiera:

```yaml
classes: ['teneleven::fpm']                                                                                                             
teneleven::fpm::extensions:                                                                                                             
  - 'curl'                                                                                                                              
  - 'gd'                                                                                                                                
  - 'intl'                                                                                                                              
  - 'mcrypt'                                                                                                                            
  - 'sqlite'                                                                                                                            
```

Just an example, and of course you'll need to provision a web server (container). I use the ```teneleven::container::nginx``` to provision vhosts (also support for a wildcard vhost, so "*.docker" goes to "/var/www/SERVER/web"). 

A lot more manual work necessary, but so far been happy. Just figured I'd plug it since puphpet (unfortunately) doesn't support docker.

**Comment by jtreminio** [comment]
@MichaelMackus you're completely welcome to suggest alternatives!
