### ISSUE TITLE
Vagrant HostUpdater

### ISSUE THREAD

**Issue by Warxcell** [puphpet/puphpet#1234]
Any chance to support https://github.com/cogitatio/vagrant-hostsupdater ? :)

**Comment by markjaquith** [comment]
vagrant-hostmanager doesn't "manage" the `/etc/hosts` file on your host machine — it adds a line on `vagrant up`, and removes the line on `vagrant destroy`, but does nothing as you bring the VM up and down with `vagrant halt` or `vagrant suspend`. So you're better off just doing this yourself.

**Comment by lachieh** [comment]
The whole point of vagrant is that it only takes one command to provision a VM. The hostsupdater plugin exists so that you don't need to add a line to your host file every time you provision a new VM or bring up an existing one.

Managing the hosts file manually is easy, yes, but if it can be done automatically, isn't that preferable?

**Comment by jtreminio** [comment]
@lachieh have you tried `$ vagrant reload`?

**Comment by lachieh** [comment]
Yeah, I just missed the fact that PuPHPet uses [vagrant-hostsmanager](https://github.com/smdahlen/vagrant-hostmanager) instead of [vagrant-hostsupdater](https://github.com/cogitatio/vagrant-hostsupdater). I didn't actually know of the latter until just now.

I've since installed hostsmanager and all is working perfectly. Sorry for the confusion.

Since hostsupdater is a popular plugin, is there any chance of supporting it as well? Not that it really matters...

**Comment by jtreminio** [comment]
@lachieh initially puphpet used hostsupdater, but ran into a bug I can't recall. That plus the fact that it hasn't been updated in a year and a half made me decide to use hostsmanager.

**Comment by lachieh** [comment]
Fair call. Like I said, hostsmanager works perfectly so it's not an issue.
It might be a good idea to make mention of hostsmanager support in the help
section on the site and the readme because without stumbling across this
issue, I wouldn't have known otherwise.

>
