### ISSUE TITLE
Add support for PHP 7.0-dev for CentOS

### ISSUE THREAD

**Issue by TiMESPLiNTER** [puphpet/puphpet#1472]
It would be great if we could add PHP 7.0-dev to the PHP version options.

I read that there's a software collection available even with a `php70-php-fpm` package.

[More information here](http://blog.famillecollet.com/post/2015/03/25/PHP-7.0-as-Software-Collection)

**Comment by jtreminio** [comment]
As soon as either Ubuntu or Debian get PHP 7 support I'll add this in. As of right now, having only a single OS with PHP7 support would make the gui start to feel too fragmented.

**Comment by TiMESPLiNTER** [comment]
Okay I thought that wouldn't be a problem because all the distributions come with different PHP versions as of now. E.x. while CentOS supports PHP from 5.4 to 5.6  (plus HHVM) Ubuntu 12.04 LTS only supports PHP 5.4 and 5.5 (plus HHVM).

**Comment by jtreminio** [comment]
I understand, but my point is that *multiple* distros support all those versions.

Since PHP7 is still so new, no one else but CentOS currently has a repo for it.

Ondrej is close, I think: https://launchpad.net/~ondrej/+archive/ubuntu/php-7.0

As soon as Ondrej or dotdeb adds support, you can be sure puphpet will be updated.

**Comment by TiMESPLiNTER** [comment]
Update: http://php7.zend.com

Now for CentOS/Debian.
