### ISSUE TITLE
Option to display the virtual machine window

### ISSUE THREAD

**Issue by thiagotalma** [puphpet/puphpet#1473]
I always edit the "Vagrantfile" file to include the line:
```virtualbox.gui = true```

I believe it would be useful to more people in this setting was PuPHPet.

Hugs!

**Comment by thiagotalma** [comment]
Can anyone help with a PR?
I have no idea how.

**Comment by jtreminio** [comment]
@thiagotalma Add the option to data.yml and defaults.yml:

https://github.com/puphpet/puphpet/tree/master/src/Puphpet/MainBundle/Resources/config/vagrantfile-local

Data should contain an empty (null) value "`~`", default should be 0 to disable it.

Then, add a hidden field to the GUI view:

https://github.com/puphpet/puphpet/blob/master/src/Puphpet/MainBundle/Resources/views/vagrantfile-local/form.html.twig

I'd prefer a hidden field because this isn't an option most users would need. Having it as a hidden field will help in carrying over an existing config file, though, so it will keep your preference if you've enabled it and drag/drop your config later.

Lastly, add it to the `Vagrantfile` here:

https://github.com/puphpet/puphpet/blob/master/archive/puphpet/vagrant/Vagrantfile-local
