### ISSUE TITLE
Authorization header is not passed using Apache

### ISSUE THREAD

**Issue by sylvainfilteau** [puphpet/puphpet#1477]
Apache 2.4 doesn't pass Authorization header to PHP under PHP-FPM and FastCGI. A workaround is to force Apache to pass the header using this configuration in VirtualHost:

````apache
SetEnvIfNoCase ^Authorization$ "(.+)" HTTP_AUTHORIZATION=$1
````

Reference: http://symfony.com/doc/current/cookbook/configuration/web_server_configuration.html#using-mod-proxy-fcgi-with-apache-2-4

**Comment by jtreminio** [comment]
You can set this under `Virtual Host-Level Custom Directives` or `Directory-Level Custom Directives`.

**Comment by sylvainfilteau** [comment]
Hi Juan, I thought you would want to add it by default. I, indeed, applied the workaround you proposed.

Thanks !

**Comment by jtreminio** [comment]
I'm trying to make all defaults for all libraries as default and vanilla as possible.

I'm proceeding under the assumption that we are all developers who will research what their specific app of choice requires.

What do you think? Should I add hints and tips somewhere? What apps should I add help for, since I know things like Wordpress, Drupal, SF2, ZF2, Laravel, etc (and etc) all have different requirements.

**Comment by sylvainfilteau** [comment]
@jtreminio I agree with you that it is not the goal of puphpet to adapt to every situation. 

But I think that this specific header (Authorization) when missing would be greatly annoying for any project. I honestly didn't check authentication with other project... but I guess any project using oauth would be affected by this issue.
