### ISSUE TITLE
Feature Request: FreeBSD

### ISSUE THREAD

**Issue by GRMule** [puphpet/puphpet#1561]
It would be fantastic to be able to provision a FreeBSD box using this tool. There doesn't seem to be many (any) solid boxes around the internet with all the usual packages one would expect for PHP development.

With all the open issues (thanks for the hard work, by the way!), this will probably be pretty low priority.

**Comment by jtreminio** [comment]
You're right, this unfortunately would be extremely low on my to-do list, for several reasons:

* Boxes are maintained via Packer [at this repo](https://github.com/puphpet/packer-templates). I'd have to figure out the steps needed to generate a FreeBSD box, since every distro is so different.
* The extra time another 3 boxes take (virtualbox, vmware, parallels) whenever I need to update the bases
* Learning how to use FreeBSD. I'm most comfortable in Debian, but since starting puphpet I've "learned" CentOS enough to be able to offer support for it
* Running through all currently available packages on the gui and making sure they're compatible with FreeBSD. My suspicion is that several would not be. In fact, I'm not even sure how FreeBSD manages pre-compiled packages, like Debian's `apt` or CentOS' `yum`. I can offer several different versions of PHP because others have been kind enough to do the work of maintaining up-to-date repos with them. This also applies to all other packages I offer, like MySQL, PostregreSQL, Mongo, Apache/Nginx, etc. I have a feeling that FreeBSD won't have as many repos available, if any, for some of these packages.

Right now my main focus are the 4 distros currently available. I am waffling on offering CentOS 7 support, and will be dropping Ubuntu 12.04 support once 16.04 comes around next year.

Debian Jessie is also on my list, whenever that comes out.

Sorry, this is far too much work for me to add to puphpet.

**Comment by GRMule** [comment]
Fair enough, thanks for the response. Keep it on a blue sky list or something though, yeah? :) Maybe someday you'll get a super-eager contributor who also happens to be a super-passionate FreeBSD expert.

P.S. Not it.
