### ISSUE TITLE
Issue with Apache when doing "up" or "provision"

### ISSUE THREAD

**Issue by Spriz** [puphpet/puphpet#1748]
Hi!

I'm trying to launch this Puphpet box with Apache and php56 - but I'm having some errors.

It failed the initial `vagrant up` - but the machine started. So I tried `vagrant provision` but the errors are more or less the same.. Could any1 see what I'm doing wrong? 

Gist with both output of "provision" and the config.yaml included:

https://gist.github.com/Spriz/28f3b8a9b9bea4fdb723

**Comment by Pryrios** [comment]
Are you running the commands with admin permissions? Seems like dpkg is failing because of not having permissions to install things. Try the commands with sudo.

**Comment by Spriz** [comment]
The vagrant up command?

**Comment by unrivaledcreations** [comment]
I'm having the exact same issue on OS/X Yosemite 10.10.4 with Vagrant 1.7.4.

@Pryrios is referring to errors in the log that read:
```
==> default: Unpacking apache2 (2.4.12-1+deb.sury.org~trusty+5) ...
==> default: dpkg: error processing archive /var/cache/apt/archives/apache2_2.4.12-1+deb.sury.org~trusty+5_amd64.deb (--unpack):
==> default:  error setting ownership of `/var/www/html.dpkg-new': Operation not permitted
```
"Operation not permitted" when "setting ownership" basically means (1) the script is running as the restricted user and it's trying to change ownership or permissions on a file; or (2) the script is running as a root user and it's trying to change ownership or permissions on a file in either a read-only file system (mounted as such, anyways) or a file system that does not support such ownership or permissions (like FAT32).

Unfortunately, Vagrant is handling all this and running Vagrant via *sudo* is a bad idea.  Further, once installing the apache2 package fails, Vagrant continues to try to finish its scripted installation, but anything to do with Apache fails:
```
==> default: Notice: /Stage[main]/Apache/Exec[mkdir /etc/apache2/mods-enabled]: Dependency Package[httpd] has failures: true
==> default: Warning: /Stage[main]/Apache/Exec[mkdir /etc/apache2/mods-enabled]: Skipping because of failed dependencies
```
Because this issue is a block, I hope @jtreminio or another suitable dev escalates this ticket's priority, although I'm not sure if it's a problem with Puphpet, Vagrant or the Apache2 distro they're using.

My log file and config.yaml:
https://gist.github.com/unrivaledcreations/489f5c57fbf4c48aa4a1

**Comment by unrivaledcreations** [comment]
Hey @Spriz - by chance, are you using VMWare's AppCatalyst with your Puphpet files?  I'm running `vagrant up --provider=vmware_appcatalyst` with a Puphpet file generated for 'VMWare Fusion,' which is causing those errors.  Using the Virtualbox configuration, Puphpet and Vagrant work faultlessly.

**Comment by Spriz** [comment]
I will try the following later!

**Comment by Spriz** [comment]
Seems to work @unrivaledcreations  :smile: :+1:

**Comment by unrivaledcreations** [comment]
Terrific, @Spriz!  Good luck with your project.  Now @jtreminio can use this information to improve the performance of PuPHPet.com to trap this uncommon error, perhaps even adding native VMWare AppCatalyst support for those of us who have moved on from VMWare Fusion.  :)

**Comment by Spriz** [comment]
Yay @unrivaledcreations !
I'm using Virtualbox though - so issue is not only with VMWare AppCatalyst :smile:

**Comment by unrivaledcreations** [comment]
In my environment, using VirtualBox did not trigger the error; meaning, `dpkg --unpack /var/cache/apt/archives/apache2_2.4.12-1+deb.sury.org~trusty+5_amd64.deb` was for some reason allowed, in *your* environment, to write to a mounted remote filesystem when provisioning.  Nonetheless, the fact that Puphpet/Vagrant is using a *mounted remote filesystem* as a *temporary local installation file destination* is problematic and should be corrected.

In any case, I'm glad I found a workaround that got us both (and possibly others) up and running!
