### ISSUE TITLE
Configuration password for default vagrant user is no longer set correctly

### ISSUE THREAD

**Issue by therightstuff** [puphpet/puphpet#2175]
I left the default configured password set to "vagrant" but was unable to log in using those credentials. I had to vagrant ssh in, manually reset the password using passwd, and then I was able to log in as usual.
This has happened to me on multiple boxes, it seems like a recently introduced bug.

**Comment by jtreminio** [comment]
Not sure if this is a puphpet-introduced change or not, but I am heavily leaning towards marking this as a feature, not a but.

You *shouldn't* be able to log in to your box using `vagrant:vagrant` - 100% of the time use the generated private key.

In fact, I would go as far as purposely disabling being able to login to the VM using username:password.

Any reason this shouldn't be done? Genuinely curious!

**Comment by Maff-** [comment]
I for one find this a bit annoying. As a Windows user I like to use kitty/putty as a ssh client, and now have to first configure the .ppk in kitty/pageant when I just want to quickly test stuff.

I use passwordless login for all remote servers, but for a local box it's nice to have quick access.

If you have some tips on how to streamline this process, it would be very welcome.

**Comment by jtreminio** [comment]
> have to first configure the .ppk in kitty/pageant when I just want to quickly test stuff.

This sounds like an issue with putty. IIRC there's a key-storing application that lets you automate some of this, but you'd still have to point to the generated key.

To be fair, this issue exists on any OS because the auto-generated key is stored in a sub directory that's not `~/.ssh`: `puphpet/files/dot/ssh/`.

However, you should be able to get around this by specifying the private key you want to use in your config.yaml.
