### ISSUE TITLE
Downgrade default apache version to 2.4.20 – Rewrite bugs in 2.4.23

### ISSUE THREAD

**Issue by oddz** [puphpet/puphpet#2397]
The current version of apache (2.4.23) that is being used has some major issues.

http://mail-archives.apache.org/mod_mbox/httpd-dev/201607.mbox/%3C57800B30.1070501@gmail.com%3E

http://mail-archives.apache.org/mod_mbox/httpd-bugs/201607.mbox/%3Cbug-59815-7868-nOscsrrU9t@https.bz.apache.org/bugzilla/%3E

I can't get any rewrites to work because of these issues. I attempted to hack the apache version in the config file but version 2.4.23 seems to still be getting downloaded.

**Comment by dragosprotung** [comment]
As a temp solution for Ubuntu 14.04 LTS x64 machines, after provisioning run
`sudo apt install apache2=2.4.10-1ubuntu1.1~ubuntu14.04.1 apache2-bin=2.4.10-1ubuntu1.1~ubuntu14.04.1 apache2-data=2.4.10-1ubuntu1.1~ubuntu14.04.1`

**Comment by jtreminio** [comment]
[This commit](https://github.com/puphpet/puppet-puphpet/commit/ab9625b18b3ab46c572946f8d093935753062cfe) adds support for defining an apache version.

In your config.yaml, do the following:

    apache:
        install: '1'
        settings:
            version: '2.4.18*'
            user: www-data
            group: www-data
            default_vhost: true
            manage_user: false
            manage_group: false
            sendfile: 0

Unfortunately, this does _not_ work in Ubuntu boxes because the repo puphpet uses only keeps the latest version in history: https://launchpad.net/~ondrej/+archive/ubuntu/apache2

This will work in CentOS, though.

If you have suggestions for an alternative repo for Ubuntu I would like to know so I can decide to switch.

**Comment by jtreminio** [comment]
I asked Ondrej about rolling back in his repo, instead he applied the patch and uploaded it: https://twitter.com/juantreminio/status/783797834755690496

So Apache 2.4.23 now has this patch in Ubuntu.

**Comment by oddz** [comment]
oh, that's great.

It really sucks only the latest version of apache (2.4.23) is in the cent-os repo.
