### ISSUE TITLE
Vagrant up: SSL_connect certificate verify failed

### ISSUE THREAD

**Issue by artisaninweb** [puphpet/puphpet#2492]
I'm getting the following error:

```
==> maxict-dev: stdin: is not a tty
==> maxict-dev: ERROR:  Could not find a valid gem 'deep_merge' (= 1.0.1), here is why:
==> maxict-dev:           Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)
==> maxict-dev: ERROR:  Could not find a valid gem 'activesupport' (= 4.2.6), here is why:
==> maxict-dev:           Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)
==> maxict-dev: ERROR:  Could not find a valid gem 'vine' (= 0.2), here is why:
==> maxict-dev:           Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

I'm searching for 5 hours now, still can't find a solution.
My dev-team is down at the moment.
Can someone please help me a.s.a.p?
THANKS!

**Comment by mike-source** [comment]
I had this issue earlier, I'm not sure of the exact problem, but I fixed it on my vagrant machine by re-syncing it with the latest version of puphpet.

With my setup the easiest way to do that is to re-upload my config.yaml file to http://puphpet.com and then re-download the archive. You then have the latest version of puphpet with all of the latest updates and fixes. If you run vagrant up on this instance it should fix the above issue (and possibly other issues you weren't aware of).

You can also just overwrite your original puphpet instance with the new one.

I keep my puphpet instance with its config.yaml and vagrantfile etc. in a git repo of its own, so I can  overwrite it with the latest changes any time I run into issues and save them in a commit so that I can easily see what's been changed and step back if needs be.

This normally works for me, hope it gets you somewhere.

**Comment by artisaninweb** [comment]
I've already tried that to.
But when i update the whole box, there's an other error i can't fix.
It's get stuck at ssh key auth.
Tried to fix that to (differtent versions of virtualbox/vagrant ect), but without any luck.

It seems that the rubygems error is comming from the version of ruby puphpet uses.
`/opt/puppetlabs/puppet/bin/gem` is a old version of gem (2.2.5).
I'm thinking this needs to be updated to the newest version (2.6.7)

Is there a way i can update the gem version in that folder?

**Comment by artisaninweb** [comment]
Fixed the problem by editing the install-puppet.sh file.
Replace:

```
 /opt/puppetlabs/puppet/bin/gem install deep_merge -v 1.0.1 --no-ri --no-rdoc
/opt/puppetlabs/puppet/bin/gem install activesupport -v 4.2.6 --no-ri --no-rdoc /opt/puppetlabs/puppet/bin/gem install vine -v 0.2 --no-ri --no-rdoc
```

With:
```
echo 'Installing newest version of rubygems'

VERSION="2.6.7"
URL="https://rubygems.org/downloads/rubygems-update-${VERSION}.gem"
LOCAL="/.puphpet-stuff/rubygems-update-${VERSION}.gem"

wget --quiet --tries=5 --connect-timeout=10 -O ${LOCAL} ${URL}

apt-get -y install rubygems

gem install --local ${LOCAL}
update_rubygems --no-ri --no-rdoc
gem uninstall rubygems-update -x

if [ $(gem -v) == ${VERSION} ]; then
    gem install deep_merge -v 1.0.1 --no-ri --no-rdoc
    gem install activesupport -v 4.2.6 --no-ri --no-rdoc
    gem install vine -v 0.2 --no-ri --no-rdoc
else
    /opt/puppetlabs/puppet/bin/gem install deep_merge -v 1.0.1 --no-ri --no-rdoc
    /opt/puppetlabs/puppet/bin/gem install activesupport -v 4.2.6 --no-ri --no-rdoc
    /opt/puppetlabs/puppet/bin/gem install vine -v 0.2 --no-ri --no-rdoc
fi
```

Maybe not the best way to do it, but it gets the job done.
