### ISSUE TITLE
(CentOS) Composer not on system path

### ISSUE THREAD

**Issue by markushausammann** [puphpet/puphpet#277]
It seems composer is not installed into the system path. If I run a shell provisioner that calls `composer` after the default puppet provisioner, I get a `composer: command not found` error.

**Comment by illepic** [comment]
I had a simple script in `exec-always` called `composer-install.sh` that looks like this:

    #!/bin/bash
    composer global install -n

And was getting the `composer: command not found` error. It turns out that I had to move the script to `exec-always-unprivileged`, probably because of composer being available to the vagrant user and not whichever user provisioning runs as.
