### ISSUE TITLE
Give permission folder writable on Win10

### ISSUE THREAD

**Issue by jdelauney** [puphpet/puphpet#2818]
Hi, i've try to give write access permission to my folder. I tried many solutionsfound on web like :
in config.yaml
> synced_folder:
>             folder1:
>                 owner: www-data  #change group and owner
>                 group: www-data
>                 source: 'c:/webdev/webroot'
>                 target: /var/www/local.dev

in vagrantfile :

> Vagrant.configure('2') do |config|
>   eval File.read("#{dir}/puphpet/vagrant/Vagrantfile-#{data['target']}")
>   config.vm.synced_folder "c:\webdev\webroot", "/var/www/local.dev", :mount_options => ['dmode=774','fmode=775']

and

>   config.vm.synced_folder "c:/webdev/webroot/", "/var/www/local.dev", :mount_options => ['uid=www-data','gid=www-data']

I'm also trie to add 

> owner:"www-data", group: "www-data", options

I tried with _vagrant ssh_ and change direcly with _chmod_ 

All without success

What the right way ? I need to have some writable folders with my php framework

for information i'm using Apache /Mysql/php 7.2 and the box is box: bento/ubuntu-16.04 and i'm using VirtualBox

Thanks in advance

Cheers

**Comment by rowanparker** [comment]
I have had many problems with folder permissions on a Windows 10 host.

In general, <i>you can't change file or folder permissions inside the guest</i>. The `chmod` or `chown` commands will run without errors, but no files will actually be changed.

The solution is to setup your development environment to work around this. The first step is to change the synced folder to be mounted as `www-data` instead of `vagrant` (as you already have done).

This will allow Apache to write to your project folder.

If you are still having issues, it's probably because your framework is specifically trying to change folder permissions (which won't work) or is at a minimum checking for folder permissions that it thinks it needs.

Usually (but not always) these folder permissions are folders that will be used for logging, caching, file uploads or maybe session files. These don't need to be inside your project folder. If your framework is half decent, you should be able to specify different locations for these. Move them to somewhere inside `/tmp`.

As the /tmp folder is not synced with your Windows 10 host, you will be able to chmod or chown as necessary.

**Comment by jdelauney** [comment]
Hi, thanks for your answer, 

> Usually (but not always) these folder permissions are folders that will be used for logging, caching, file uploads or maybe session files

It's exactly for this ;) Not a problem i can easly change path if i need.

This morning

after clean the config.yaml and apply changes like this

> owner: www-data
> group: www-data
> source: 'c:/webdev/webroot'
> target: /var/www/local.dev
> sync_type: default

Don't choose sync_type:nfs on w10 !!!

and in vagrantfile

>   config.vm.synced_folder "c:/webdev/webroot/", "/var/www/local.dev", :mount_options => ['uid=www-data','gid=www-data']

After restart my PC and do vagrant-up all is done. But yesterday i've applied a chmod
Soi don't say if the chmod is really needed. But i think this problems come from VirtualBox or is a security in Windows 10 with the changes in the Host. The trick seems to be just need to restart PC

Cheers and thank for your help
